services:
  dash-app:
    build: .
    container_name: mi_app_dash
    ports:
      - "8050:8050"
    volumes:
      - ./Datasets:/app/Datasets
      - ./debug:/app/debug
    environment:
      - DASH_DEBUG_MODE=True
      - EpochDataset=/
      - TimeDataset=/app
    deploy:
      resources:
        limits:
          memory: 6G
          cpus: '2.0'
        reservations:
          memory: 2G
    restart: unless-stopped